let pkmnSeed = `CREATE TABLE IF NOT EXISTS Pokemon (id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
generation TEXT NOT NULL,
hp INTEGER,
attack INTEGER,
defense INTEGER,
special_attack INTEGER,
special_defense INTEGER,
speed INTEGER,
primary_type TEXT NOT NULL,
secondary_type TEXT,
ability_i TEXT NOT NULL,
ability_ii TEXT,
hidden_ability TEXT,
ev_worth TEXT,
gender TEXT,
egg_group_i TEXT,
egg_group_ii TEXT,
catch INTEGER,
evolve TEXT);`;

let moveSeed = `CREATE TABLE IF NOT EXISTS Moves (id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
type TEXT NOT NULL,
category TEXT,
power INTEGER,
accuracy INTEGER,
pp INTEGER,
effect TEXT,
probability INTEGER);`;

let pkmnMovesSeed = `CREATE TABLE IF NOT EXISTS Pokemon_Moves (pokemon_id INT NOT NULL REFERENCES Pokemon(id),
move_id INT NOT NULL REFERENCES Moves(id),
PRIMARY KEY (pokemon_id, move_id));`;

